### ISSUE TITLE
Uncaught TypeError: task.replaceAll is not a function

### ISSUE THREAD

**Issue by ghost** [henjue/atom-gradle-manager#3]
after install 

show a error 
**Atom Version**: 1.3.1
**System**: Unknown Windows Version
**Thrown From**: [gradle-manager](https://github.com/henjue/atom-gradle-manager) package, v0.0.3
### Stack Trace

Uncaught TypeError: task.replaceAll is not a function

```
At /C:/Users/yanliang01/.atom/packages/gradle-manager/lib/ParserUtil.coffee:10

TypeError: task.replaceAll is not a function
    at ParserFactory.filter (file:///C:/Users/yanliang01/.atom/packages/gradle-manager/lib/ParserUtil.coffee:7:18)
    at ParserFactory.<anonymous> (file:///C:/Users/yanliang01/.atom/packages/gradle-manager/lib/ParserUtil.coffee:20:53)
    at ParserFactory.parser (file:///C:/Users/yanliang01/.atom/packages/gradle-manager/lib/ParserUtil.coffee:20:20)
    at file:///C:/Users/yanliang01/.atom/packages/gradle-manager/lib/views/output-view.coffee:39:23
    at triggerExitCallback (C:\Users\yanliang01\AppData\Local\atom\app-1.3.1\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\yanliang01\AppData\Local\atom\app-1.3.1\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -4:29.3.0 build:select-active-target (atom-text-editor.editor.is-focused)
     -4:26.5.0 build:trigger (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -3:42.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:38.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:45.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:14.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.3.6
build, v0.50.0
build-make, v0.4.0
build-npm-apm, v0.5.0
build-sbt, v0.1.0
gradle-manager, v0.0.3
java-importer, v1.4.1
language-gradle, v0.0.3
language-groovy, v0.4.0
minimap, v4.18.0
pigments, v0.19.3

# Dev
No dev packages
```

**Comment by springeye** [comment]
@nathanyan I already know this question, I will deal with it recently!

**Comment by springeye** [comment]
@nathanyan fixed
